apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-ex-out3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ex-out3
    app.kubernetes.io/part-of: my-app
  name: python-ex-out3
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-ex-out3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-ex-out3
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:6dd8de9ebda433ca4393d53f9145f45ea87b827fe0fb0f0a50855b0d72f0f749
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8084
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
