apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-ex-out3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ex-out3
    app.kubernetes.io/part-of: my-app
  name: python-ex-out3
  namespace: mdsaud-tenant
spec:
  path: /
  port:
    targetPort: 8082
  to:
    kind: Service
    name: python-ex-out3
    weight: null
status: {}
