apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-ex-out3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ex-out3
    app.kubernetes.io/part-of: my-app
  name: python-ex-out3
  namespace: mdsaud-tenant
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app.kubernetes.io/instance: python-ex-out3
status:
  loadBalancer: {}
