apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nw62
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nw62
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-nw62
  namespace: mdsaud-tenant
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: devfile-sample-nw62
status:
  loadBalancer: {}
