apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nw62
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:b86513c28ba0e63012733e585c1258cba0bae03f6a67f0c1db2611f359847bea
        name: my-nodejs
        resources: {}
status: {}
