apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dx7e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dx7e
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-dx7e
  namespace: mdsaud-tenant
spec:
  ports:
  - port: 2999
    targetPort: 2999
  selector:
    app.kubernetes.io/instance: devfile-sample-dx7e
status:
  loadBalancer: {}
