apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-ex-out3
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:6dd8de9ebda433ca4393d53f9145f45ea87b827fe0fb0f0a50855b0d72f0f749
        name: my-python
        resources: {}
status: {}
